---
# {{{ Fonts
my_fonts:
  - hack
# }}}

# {{{ Terminal Profiles
terminal_profiles:
  - Peppermint
# }}}

downloads: ~/.ansible-downloads/

# {{{ Dock Items | Enabled
dockitems_enabled: []
# }}}

# {{{ Dock Items | Disabled
dockitems_disabled:
  - Siri
  - Launchpad
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Pages
  - Numbers
  - Keynote
  - iTunes
  - iBooks
  - App Store
  - System Preferences
# }}}

# {{{ Brew Packages
homebrew_installed_packages:
  - autoconf
  - aspell
  - augeas
  - colordiff
  - dockutil
  - fabric
  - geoip
  - gawk
  - git
  - hub
  - ipcalc
  - iperf
  - jq
  - minicom
  - mtr
  - nmap
  - npm
  - nvm
  - packer
  - ssh-copy-id
  - readline
  - reattach-to-user-namespace
  - rename
  - shellcheck
  - speedtest_cli
  - ssh-copy-id
  - task
  - tig
  - tmux
  - urlview
  - watch
  - weechat
  - wget
  - zsh-completions
# }}}

# {{{ Brew Taps
homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions
# }}}

homebrew_cask_appdir: /Applications
# {{{ Brew Cask Apps
homebrew_cask_apps:
  - 1password
  - alfred
  - atom
  - authy-desktop
  - bartender
  - burn
  - discord
  - docker
  - dropbox
  - easysimbl
  - filezilla
  - firefox
  - google-chrome
  - gpgtools
  - handbrake
  - istat-menus
  - kdiff3
  - little-snitch
  - macdown
  - macvim
  - makemkv
  - qblocker
  - ripit
  - totalspaces
  - tunnelblick
  - unrarx
  - slack
  - the-unarchiver
  - vagrant
  - virtualbox
  - vlc
  - vmware-fusion
  - xquartz
# }}}

# {{{ Global Python PIPs
system_global_pips: []
# }}}

# {{{ Global Ruby GEMs
system_global_gems:
  - name: tmuxinator
    version: 0.9.0
  - name: hiera-eyaml
    version: 2.1.0
  - name: bundler
    version: 1.15.3
# }}}
